In [ ]:
!pip install -q pandas numpy scikit-learn joblib openpyxl

In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

import joblib

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving bodyPerformance.csv to bodyPerformance.csv

In [ ]:
df = pd.read_csv("bodyPerformance.csv")

df.head()

,age,gender,height_cm,weight_kg,body fat_%,diastolic,systolic,gripForce,sit and bend forward_cm,sit-ups counts,broad jump_cm,class
0,27.0,M,172.3,75.24,21.3,80.0,130.0,54.9,18.4,60.0,217.0,C
1,25.0,M,165.0,55.80,15.7,77.0,126.0,36.4,16.3,53.0,229.0,A
2,31.0,M,179.6,78.00,20.1,92.0,152.0,44.8,12.0,49.0,181.0,C
3,32.0,M,174.5,71.10,18.4,76.0,147.0,41.4,15.2,53.0,219.0,B
4,28.0,M,173.8,67.70,17.1,70.0,127.0,43.5,27.1,45.0,217.0,B

In [ ]:
print(df.shape)

df.info()

df.isnull().sum()

(13393, 12)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13393 entries, 0 to 13392
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   age                      13393 non-null  float64
 1   gender                   13393 non-null  object
 2   height_cm                13393 non-null  float64
 3   weight_kg                13393 non-null  float64
 4   body fat_%               13393 non-null  float64
 5   diastolic                13393 non-null  float64
 6   systolic                 13393 non-null  float64
 7   gripForce                13393 non-null  float64
 8   sit and bend forward_cm  13393 non-null  float64
 9   sit-ups counts           13393 non-null  float64
 10  broad jump_cm            13393 non-null  float64
 11  class                    13393 non-null  object
dtypes: float64(10), object(2)
memory usage: 1.2+ MB

age                        0
gender                     0
height_cm                  0
weight_kg                  0
body fat_%                 0
diastolic                  0
systolic                   0
gripForce                  0
sit and bend forward_cm    0
sit-ups counts             0
broad jump_cm              0
class                      0
dtype: int64

In [ ]:
df["BMI"] = df["weight_kg"] / ((df["height_cm"]/100)**2)

df.head()

,age,gender,height_cm,weight_kg,body fat_%,diastolic,systolic,gripForce,sit and bend forward_cm,sit-ups counts,broad jump_cm,class,BMI
0,27.0,M,172.3,75.24,21.3,80.0,130.0,54.9,18.4,60.0,217.0,C,25.344179
1,25.0,M,165.0,55.80,15.7,77.0,126.0,36.4,16.3,53.0,229.0,A,20.495868
2,31.0,M,179.6,78.00,20.1,92.0,152.0,44.8,12.0,49.0,181.0,C,24.181428
3,32.0,M,174.5,71.10,18.4,76.0,147.0,41.4,15.2,53.0,219.0,B,23.349562
4,28.0,M,173.8,67.70,17.1,70.0,127.0,43.5,27.1,45.0,217.0,B,22.412439

In [ ]:
gender_encoder = LabelEncoder()

df["gender"] = gender_encoder.fit_transform(df["gender"])

In [ ]:
class_encoder = LabelEncoder()

df["class"] = class_encoder.fit_transform(df["class"])

print(class_encoder.classes_)

['A' 'B' 'C' 'D']

In [ ]:
X = df[
    [
        "age",
        "gender",
        "height_cm",
        "weight_kg",
        "BMI",
        "body fat_%",
        "gripForce",
        "sit and bend forward_cm",
        "sit-ups counts",
        "broad jump_cm"
    ]
]

y = df["class"]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [ ]:
model = RandomForestClassifier(
    n_estimators=300,
    random_state=42
)

model.fit(X_train, y_train)

RandomForestClassifier(n_estimators=300, random_state=42)

In [ ]:
pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, pred))

print(classification_report(y_test, pred))

Accuracy: 0.7525195968645016
              precision    recall  f1-score   support

           0       0.75      0.85      0.79       685
           1       0.63      0.62      0.63       662
           2       0.73      0.71      0.72       650
           3       0.92      0.82      0.87       682

    accuracy                           0.75      2679
   macro avg       0.76      0.75      0.75      2679
weighted avg       0.76      0.75      0.75      2679

In [ ]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=500,
    max_depth=15,
    min_samples_split=5,
    min_samples_leaf=2,
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)

RandomForestClassifier(max_depth=15, min_samples_leaf=2, min_samples_split=5,
                       n_estimators=500, n_jobs=-1, random_state=42)

In [ ]:
pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, pred))
print(classification_report(y_test, pred))

Accuracy: 0.7547592385218365
              precision    recall  f1-score   support

           0       0.75      0.86      0.80       685
           1       0.63      0.63      0.63       662
           2       0.73      0.71      0.72       650
           3       0.92      0.82      0.87       682

    accuracy                           0.75      2679
   macro avg       0.76      0.75      0.75      2679
weighted avg       0.76      0.75      0.76      2679

In [ ]:
import joblib

# Save model
joblib.dump(model, "fitness_level_model.pkl")

# Save encoders
joblib.dump(gender_encoder, "gender_encoder.pkl")
joblib.dump(class_encoder, "class_encoder.pkl")

print("Model saved successfully!")

Model saved successfully!

In [ ]:
from google.colab import files

files.download("fitness_level_model.pkl")
files.download("gender_encoder.pkl")
files.download("class_encoder.pkl")

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving programs_detailed_boostcamp_kaggle.csv to programs_detailed_boostcamp_kaggle.csv

In [ ]:
import pandas as pd

workout_df = pd.read_csv("programs_detailed_boostcamp_kaggle.csv")

workout_df.head()

,title,description,level,goal,equipment,program_length,time_per_workout,week,day,number_of_exercises,exercise_name,sets,reps,intensity,created,last_edit
0,Weightlifting Mobility program,This program is designed to help athletes succ...,"['Beginner', 'Novice', 'Intermediate', 'Advanc...","['Olympic Weightlifting', 'Muscle & Sculpting'...",Garage Gym,7.0,50.0,1.0,1.0,16.0,Knee-to-wall ankle dorsiflexion test,3.0,-180.0,6.0,2025-03-09 04:11:00,2025-06-23 03:31:00
1,Weightlifting Mobility program,This program is designed to help athletes succ...,"['Beginner', 'Novice', 'Intermediate', 'Advanc...","['Olympic Weightlifting', 'Muscle & Sculpting'...",Garage Gym,7.0,50.0,1.0,1.0,16.0,Banded ankle distractions,3.0,-18.0,6.0,2025-03-09 04:11:00,2025-06-23 03:31:00
2,Weightlifting Mobility program,This program is designed to help athletes succ...,"['Beginner', 'Novice', 'Intermediate', 'Advanc...","['Olympic Weightlifting', 'Muscle & Sculpting'...",Garage Gym,7.0,50.0,1.0,1.0,16.0,Slant board calf stretch,3.0,-18.0,6.0,2025-03-09 04:11:00,2025-06-23 03:31:00
3,Weightlifting Mobility program,This program is designed to help athletes succ...,"['Beginner', 'Novice', 'Intermediate', 'Advanc...","['Olympic Weightlifting', 'Muscle & Sculpting'...",Garage Gym,7.0,50.0,1.0,1.0,16.0,Seated Tibialis Raise,3.0,15.0,6.0,2025-03-09 04:11:00,2025-06-23 03:31:00
4,Weightlifting Mobility program,This program is designed to help athletes succ...,"['Beginner', 'Novice', 'Intermediate', 'Advanc...","['Olympic Weightlifting', 'Muscle & Sculpting'...",Garage Gym,7.0,50.0,1.0,1.0,16.0,90/90 Hip Rotations,3.0,8.0,6.0,2025-03-09 04:11:00,2025-06-23 03:31:00

In [ ]:
print(workout_df.columns)

print(workout_df.shape)

workout_df.info()

workout_df.isnull().sum()

Index(['title', 'description', 'level', 'goal', 'equipment', 'program_length',
       'time_per_workout', 'week', 'day', 'number_of_exercises',
       'exercise_name', 'sets', 'reps', 'intensity', 'created', 'last_edit'],
      dtype='object')
(605033, 16)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 605033 entries, 0 to 605032
Data columns (total 16 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   title                605033 non-null  object
 1   description          604214 non-null  object
 2   level                605033 non-null  object
 3   goal                 605033 non-null  object
 4   equipment            605017 non-null  object
 5   program_length       605017 non-null  float64
 6   time_per_workout     605033 non-null  float64
 7   week                 605033 non-null  float64
 8   day                  605033 non-null  float64
 9   number_of_exercises  605033 non-null  float64
 10  exercise_name        605033 non-null  object
 11  sets                 605033 non-null  float64
 12  reps                 605033 non-null  float64
 13  intensity            605033 non-null  float64
 14  created              605017 non-null  object
 15  last_edit            604992 non-null  object
dtypes: float64(8), object(8)
memory usage: 73.9+ MB

title                    0
description            819
level                    0
goal                     0
equipment               16
program_length          16
time_per_workout         0
week                     0
day                      0
number_of_exercises      0
exercise_name            0
sets                     0
reps                     0
intensity                0
created                 16
last_edit               41
dtype: int64

In [ ]:
print(workout_df.columns.tolist())

['title', 'description', 'level', 'goal', 'equipment', 'program_length', 'time_per_workout', 'week', 'day', 'number_of_exercises', 'exercise_name', 'sets', 'reps', 'intensity', 'created', 'last_edit']

In [ ]:
workout_df = workout_df.drop(columns=["description","created","last_edit"])

workout_df = workout_df.dropna()

workout_df.head()

,title,level,goal,equipment,program_length,time_per_workout,week,day,number_of_exercises,exercise_name,sets,reps,intensity
0,Weightlifting Mobility program,"['Beginner', 'Novice', 'Intermediate', 'Advanc...","['Olympic Weightlifting', 'Muscle & Sculpting'...",Garage Gym,7.0,50.0,1.0,1.0,16.0,Knee-to-wall ankle dorsiflexion test,3.0,-180.0,6.0
1,Weightlifting Mobility program,"['Beginner', 'Novice', 'Intermediate', 'Advanc...","['Olympic Weightlifting', 'Muscle & Sculpting'...",Garage Gym,7.0,50.0,1.0,1.0,16.0,Banded ankle distractions,3.0,-18.0,6.0
2,Weightlifting Mobility program,"['Beginner', 'Novice', 'Intermediate', 'Advanc...","['Olympic Weightlifting', 'Muscle & Sculpting'...",Garage Gym,7.0,50.0,1.0,1.0,16.0,Slant board calf stretch,3.0,-18.0,6.0
3,Weightlifting Mobility program,"['Beginner', 'Novice', 'Intermediate', 'Advanc...","['Olympic Weightlifting', 'Muscle & Sculpting'...",Garage Gym,7.0,50.0,1.0,1.0,16.0,Seated Tibialis Raise,3.0,15.0,6.0
4,Weightlifting Mobility program,"['Beginner', 'Novice', 'Intermediate', 'Advanc...","['Olympic Weightlifting', 'Muscle & Sculpting'...",Garage Gym,7.0,50.0,1.0,1.0,16.0,90/90 Hip Rotations,3.0,8.0,6.0

In [ ]:
def level_map(level):
    level = str(level).lower()

    if "beginner" in level:
        return "D"

    elif "intermediate" in level:
        return "C"

    elif "advanced" in level:
        return "B"

    elif "elite" in level:
        return "A"

    else:
        return "C"

workout_df["fitness_level"] = workout_df["level"].apply(level_map)

In [ ]:
import joblib

joblib.dump(workout_df, "workout_database.pkl")

['workout_database.pkl']

In [ ]:
from google.colab import files

files.download("workout_database.pkl")